### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by arkD** [immortal-sniper1/fast_trans_#1]
tried installing your 1.18 version of this mod and got this error:
__fast_trans__/data.lua:4:__fast_trans__/prototypes/entity.lua:1438: attempt to call global 'generic_impact_sound' (a nil value)
stack traceback:
__fast_trans__/prototypes/entity.lua:4: in main chunk
[C]: in function 'require'
__fast_trans__/data.lua:4:in main chunk

I believe you can use vehicle_impact_sound instead to fix for 1.18.

**Comment by immortal-sniper1** [comment]
it must me the 0.18.2 version 
it worked well in 0.18

well i will fix it tonight or tomorrow

**Comment by arkD** [comment]
ah makes sense, just part of the cost of being experimental. thanks for the quick response

**Comment by immortal-sniper1** [comment]
code is ok but for some reason refferences are not working , it is the same problem is other mods too, i will look deeper into it

**Comment by immortal-sniper1** [comment]
0.18.3 is out i will test and fix it for that too , release is delayed AGAIN

**Comment by arkD** [comment]
no problem. thank you for being on the ball.

**Comment by immortal-sniper1** [comment]
fix found testing it in ffff mod since it is smaller

**Comment by arkD** [comment]
great, looking forward to testing it out

**Comment by immortal-sniper1** [comment]
didnt work , testing a few other ideas

**Comment by immortal-sniper1** [comment]
ffff is done i think i figured it out

**Comment by immortal-sniper1** [comment]
it is updated , working but no collision sound and i made them cheeper
